#!/bin/bash

# Argomenti:
# $1: File contenente il messaggio di commit
# $2: Tipo di commit (opzionale: es. merge, squash)
# $3: SHA del commit (opzionale, per commit amend)

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
PREFIX_NUMBER=$(echo "$BRANCH_NAME" | grep -o '^[0-9]*')

# Verifica che non sia un commit generato automaticamente (es. merge, squash)
if [[ "$2" != "merge" && "$2" != "squash" ]]; then
  # Verifica che il numero del branch esista e non sia già nel messaggio
  if [[ -n "$PREFIX_NUMBER" ]]; then
    if ! grep -q "(#$PREFIX_NUMBER)" "$1"; then
      # Aggiunge la parentesi alla fine della prima riga
      sed -i "1s/\$/ (#$PREFIX_NUMBER)/" "$1"
    fi
  fi
fi
